apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
   containers:
      - name: my-ngnix
        image: nginx:latest
        ports:
         - containerPort: 80
        volumeMounts:
          - name: hostpath-vol
            mountPath: '/var/arun'

   volumes:
     - name: hostpath-vol
       hostpath:
          path: '/home/ubuntu/pod_data'
          type: DirectorOrCreate